name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BOOST_SOURCE_URL: https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.bz2
  BOOST_SOURCE_NAME: boost_1_82_0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y liburing-dev cmake

    - name: Cache Boost Download
      id: cache-boost-download
      uses: actions/cache@v3
      with:
        path: ${{env.BOOST_SOURCE_NAME}}.tar.bz2
        key: boost-download

    - name: Download Boost
      if: steps.cache-boost-download.outputs.cache-hit != 'true'
      run: wget "${{env.BOOST_SOURCE_URL}}"

    - name: Cache Boost Build
      id: cache-boost-build
      uses: actions/cache@v3
      with:
        path: ${{env.BOOST_SOURCE_NAME}}
        key: build-boost

    - name: Build Boost
      if: steps.cache-boost-build.outputs.cache-hit != 'true'
      run: |
        tar -xf ${{env.BOOST_SOURCE_NAME}}.tar.bz2
        cd ${{env.BOOST_SOURCE_NAME}}
        ./bootstrap.sh
        sudo ./b2 \
          --without-graph \
          --without-graph_parallel \
          --without-mpi \
          --without-python \
          --without-wave \
          variant=release link=shared threading=multi \
          install

    - name: Re-install Boost
      if: steps.cache-boost-build.outputs.cache-hit == 'true'
      run: |
        cd ${{env.BOOST_SOURCE_NAME}}
        sudo ./b2 \
          --without-graph \
          --without-graph_parallel \
          --without-mpi \
          --without-python \
          --without-wave \
          variant=release link=shared threading=multi \
          install

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   # Execute tests defined by the CMake configuration.
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest -C ${{env.BUILD_TYPE}}

